### ISSUE TITLE
CRUD operations doesn't work when id property is defined in json file

### ISSUE THREAD

**Issue by hgouveia** [strongloop/loopback-connector-mongodb#255]
CRUD operations doesn't work when the id property is defined in json file

I created a simple model using `slc arc` named **City**, then i went to explorer , make a simple **POST** to create a new **City** ,this works, but then i tried with the **DELETE** request, using the id of the created item, and the result is `{ count : 0 }` ,and should be `{ count : 1}` , this issue happends also with another CRUD operations via HTTP Request or working directly in code , this is the model created via `slc arc`

```
{
  "name": "City",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "index": true
    },
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

now this is the weird part, if i remove the id property from the .json and leave the model like this 

```
{
  "name": "City",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

```

it works, i got { count : 1 }, why with the id property fail? 

i tried node 0.12.9 , 4.4.0 and 5.0.0 , also tried loopback 2.22.0, and 2.5.0 , and latest 2.29.0 , in windows and ubuntu 14 LTS,  mongo 2.4.9 and 3.2, nothing works 

I've used the [loopback-getting-started](https://github.com/strongloop/loopback-getting-started) to do this test , and updated the code to use  loopback mongo connector

probably related [issue](https://github.com/strongloop/loopback-connector-mongodb/issues/52)

**Comment by renanwilliam** [comment]
Facing the same situation here.

**Comment by jannyHou** [comment]
Confirmed it's a bug.

**Comment by manasmishra** [comment]
I think this issue has been fixed, please check it once. If so please close this bug.

**Comment by jannyHou** [comment]
@manasmishra thank you I will confirm again asap.

**Comment by sovattha** [comment]
The issue is not fixed from my perspective but the issue is slightly different.

I have a Customer owning multiple Vehicles.
I can create/read/update customers.
I *CAN* read the vehicles of the customers, but *CANNOT* edit them. 

Both use autogenerated ids.

customer.json
```
{
  "name": "Customer",
  "description": [
    "Customers"
  ],
  "plural": "customers",
  "base": "PersistedModel",
  "idInjection": true,
```

vehicle.json
```
{
  "name": "Vehicle",
  "description": [
    "Vehicles of one customer"
  ],
  "plural": "vehicles",
  "base": "PersistedModel",
  "idInjection": true,
```

Response from PUT /customers/{id}/vehicles/{fk}
```json
{
  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Aucune instance avec id 58db6737fea556095e0be99f trouvée pour Vehicle"
  }
}
```

The Vehicle uses an ObjectId().

If I set their vehicles ID manually, so that Vehicle use ID strings, I can then read/update/delete them.

**Comment by jannyHou** [comment]
@sovattha might be same problem with https://github.com/strongloop/loopback-connector-mongodb/issues/302

Can you try set `strictObjectIDCoercion: false` in model's options?

**Comment by sovattha** [comment]
I tried to set `strictObjectIDCoercion: false` in both models.

I can create customers and attach vehicles and I can read customers but cannot read their vehicles.
It expect the foreign key in Vehicle to be an ObjectId and not a string. 
Example:

I create a vehicle
`POST /customers/{id}/vehicles`
Request body is
```json
{
  "vehicleManufacturer": "Audi",
  "vehicleModel": "TT2",
  "vehicleRegistrationPlateIdentifier": "AA123BB"
}
```

Response is
```json
{
  "vehicleId": "58dbcd1d036b2631fcc319f2",
  "vehicleManufacturer": "Audi",
  "vehicleModel": "TT2",
  "vehicleRegistrationPlateIdentifier": "AA123BB",
  "customerId": "58dbccdd036b2631fcc319f1"
}
```

This is the record I get in MongoDB
```json
{
    "_id" : ObjectId("58dbcd1d036b2631fcc319f2"),
    "vehicleManufacturer" : "Audi",
    "vehicleModel" : "TT2",
    "vehicleRegistrationPlateIdentifier" : "AA123BB",
    "customerId" : "58dbccdd036b2631fcc319f1"
}
```

`GET /customers/{id}/vehicles` (where of course id is 58dbccdd036b2631fcc319f1)
gets a 404

In MongoDB when I change **manually** the customerId in vehicles from string to ObjectId, it works: I can find my vehicles again. 

My record becomes:

```json
{
    "_id" : ObjectId("58dbcd1d036b2631fcc319f2"),
    "vehicleManufacturer" : "Audi",
    "vehicleModel" : "TT2",
    "vehicleRegistrationPlateIdentifier" : "AA123BB",
    "customerId" : ObjectId("58dbccdd036b2631fcc319f1")
}
```

`GET /customers/{id}/vehicles`
gets a proper response

```json
[
  {
    "vehicleId": "58dbcd1d036b2631fcc319f2",
    "vehicleManufacturer": "Audi",
    "vehicleModel": "TT2",
    "vehicleRegistrationPlateIdentifier": "AA123BB",
    "customerId": "58dbccdd036b2631fcc319f1"
  }
]
```

Then if I edit my vehicle with a 
`PUT /customers/{id}/vehicles/{fk}`

```json
  {
    "vehicleManufacturer": "Audi",
    "vehicleModel": "TT3",
    "vehicleRegistrationPlateIdentifier": "AA123BB"
  }
```

The response is

```
{
  "vehicleId": "58dbcd1d036b2631fcc319f2",
  "vehicleManufacturer": "Audi",
  "vehicleModel": "TT3",
  "vehicleRegistrationPlateIdentifier": "AA123BB",
  "customerId": "58dbccdd036b2631fcc319f1"
}
```

And the foreign key customerId remains an ObjectId in MongoDB.

```json
{
    "_id" : ObjectId("58dbcd1d036b2631fcc319f2"),
    "vehicleManufacturer" : "Audi",
    "vehicleModel" : "TT3",
    "vehicleRegistrationPlateIdentifier" : "AA123BB",
    "customerId" : ObjectId("58dbccdd036b2631fcc319f1")
}
```

Version 1.17.0 worked well with the foreign key being a string. It created a string and kept a string all the way long.

**Comment by ssh24** [comment]
The original intent of this issue is fixed and can confirm it is not a bug. 

Here is an example code snippet:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "required": true,
      "id": true
    },
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var Employee = app.models.Employee;

  var data = [{
    id: 1,
    name: 'Foo',
  }, {
    id: 2,
    name: 'Bar',
  }, {
    id: 3,
    name: 'Baz',
  }, {
    id: 4,
    name: 'Bob',
  }, {
    id: 5,
    name: 'Sam',
  }];

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('\nAutomigrate complete');

    Employee.create(data, function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result));
    });
  });
};
```

**output**
```bash
sakibs-mac:mongodb-255 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate complete

Created instance: [ { id: 1, name: 'Foo' },
  { id: 2, name: 'Bar' },
  { id: 3, name: 'Baz' },
  { id: 4, name: 'Bob' },
  { id: 5, name: 'Sam' } ]
```

Closing this story as a result. Feel free to reopen if needed.
