### ISSUE TITLE
Error when querying mongodb with AND as well as near

### ISSUE THREAD

**Issue by willyyr** [strongloop/loopback-connector-mongodb#49]
When using a mongo db datasource and trying to query a model by using the and operator it fails when using "near" as well. 

Query: 
`{"where": {"and": [{"location": {"near": "52.335421, 13.096018"}},{"name": {"like": "aus"}}]}}`

Error:  
`"message": "Can't canonicalize query: BadValue not handled: $near",
 "stack": "MongoError: Can't canonicalize query: BadValue not handled: $near\n    at Object.toError (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/utils.js:114:11)\n    at /home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:689:54\n    at Cursor.close (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:972:5)\n    at commandHandler (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:689:21)\n    at /home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/db.js:1847:9\n    at Server.Base._callHandler (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)\n    at /home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/server.js:478:18\n    at MongoReply.parseBody (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)\n    at null.<anonymous> (/home/codio/workspace/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)\n    at EventEmitter.emit (events.js:95:17)"`

Switching the model to in memory this query works just fine.

**Comment by raymondfeng** [comment]
Mongodb `$near` needs to take a [lat, lng].

**Comment by rejunrajreju** [comment]
I get a different error while executing the code bellow

Car.find({filter:{   "where": {"and":[{"geop": {"near": [ lat, long ],maxDistance:5} }, {"name":carname }]} }},function(d){})

{"error":{"name":"MongoError","status":500,"message":"n/a","$err":"Unable to execute query: error processing query: ns=qataryellow.main limit=1000 skip=0\nTree: $and\n    name == \"Auto Body Repair\"\n    GEONEAR  field=geop maxdist=1.79769e+308 isNearSphere=0\nSort: { _id: 1 }\nProj: {}\n planner returned error: unable to find index for $geoNear query","code":17007,"stack":"Error\n    at Error.MongoError (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:13:17)\n    at Function.MongoError.create (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n    at queryCallback (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:170:34)\n    at /Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17\n    at b (domain.js:183:18)\n    at Callbacks.emit (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)\n    at null.messageHandler (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:209:23)\n    at Socket.<anonymous> (/Users/rejunrajck/projects/qatar/yellowserve/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:256:22)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:765:14)"}}

**Comment by rejunrajreju** [comment]
I get a different error while executing the code bellow

Car.find({filter:{   "where": {"and":[{"geop": {"near": [ lat, long ],maxDistance:5} }, {"name":carname }]} }},function(d){})

{"error":{"name":"MongoError","status":500,"message":"n/a","$err":"Unable to execute query: error processing query: ns=qataryellow.main limit=1000 skip=0\nTree: $and\n    name == \"Benz\"\n    GEONEAR  field=geop maxdist=1.79769e+308 isNearSphere=0\nSort: { _id: 1 }\nProj: {}\n planner returned error: unable to find index for $geoNear query","code":17007,"stack":"Error\n    at Error.MongoError 


I get the expected result if i takeoff `and` and give only one condition

Car.find({filter:{   "where": {"geop": {"near": [ lat, long ],maxDistance:5} } }},function(d){})

**Comment by willyyr** [comment]
@raymondfeng i thought the notation is backend-agnostic? That's why I used to notation as documented.

**Comment by kwiky** [comment]
@rejunrajreju @willyyr @raymondfeng Please HELP :'( 
I have the same problem : 
I can't use the near condition if it's in a "and" object

Works : 
{"where":{"location":{"near":[47.4722343,-0.5507339]}},"skip":0,"limit":100}

Don't works : 
{"where":{"and":[{"location":{"near":[47.4722343,-0.5507339]}},{"jobType":"COOPERATIVE"}]},"skip":0,"limit":100}

It returns : 
{"error":{"name":"MongoError","status":500,"message":"n/a","$err":"Unable to execute query: error processing query: ns=thales02.job limit=100 skip=0\nTree: $and\n    jobType == \"COOPERATIVE\"\n    GEONEAR  field=location maxdist=1.79769e+308 isNearSphere=0\nSort: { posted: -1 }\nProj: {}\n planner returned error: unable to find index for $geoNear query","code":17007}}

**Comment by kwiky** [comment]
It's maybe because the query is transformed in the first case here : 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L7

and not in the second case...

**Comment by kwiky** [comment]
I just realize that, in the first case, the near criteria is not passed to mongodb but executed in the geo.js file in loopback-datasource-juggler.

In the second case, the parameter is given to mongodb.
I have to add a 2dsphere indexe and use the $nearSphere criteria in this case : 
{"where":{"and":[{"location":{"nearSphere":[47.4722343,-0.5507339]}},{"jobType":"COOPERATIVE"}]},"skip":0,"limit":100}

**Comment by zakuapps** [comment]
@kwiky I followed your tips, but without success. When I use the nearSphere criteria the results are not filtered by location. Any ideas?

**Comment by kwiky** [comment]
@zakuapps have you create your 2dsphere indexe ?
http://docs.mongodb.org/manual/tutorial/build-a-2dsphere-index/

**Comment by zakuapps** [comment]
yes, thanks. Anyway, I found the issue. 

I'm using the maxDistance filter, and I realized that it is never passed to mongodb (when I use the "and" operator). That's why the results weren't filtered.

I've just solved by replacing the MongoDB "buildWhere" defined in mongodb.js with the following one:

```javascript
 MongoDB.prototype.buildWhere = function (model, where) {
  var self = this;
  var query = {};
  if (where === null || (typeof where !== 'object')) {
    return query;
  }
  var idName = self.idName(model);
  Object.keys(where).forEach(function (k) {
    var cond = where[k];
    if (k === idName) {
      k = '_id';
      cond = ObjectID(cond);
    }
    if (k === 'and' || k === 'or' || k === 'nor') {
      if (Array.isArray(cond)) {
        cond = cond.map(function (c) {
          return self.buildWhere(model, c);
        });
      }
      query['$' + k ] = cond;
      delete query[k];
      return;
    }
    var spec = false;
    var options = null;
    var _cond = false;

    if (cond && cond.constructor.name === 'Object') {
      options = cond.options;
      query[k] = {};

      Object.keys(cond).forEach(function (spec) {

        _cond = cond[spec];

        if (spec) {
          if (spec === 'between') {
            query[k] = {$gte: _cond[0], $lte: _cond[1]};
          } else if (spec === 'inq') {
            query[k] = {
              $in: _cond.map(function (x) {
                if ('string' !== typeof x) return x;
                return ObjectID(x);
              })
            };
          } else if (spec === 'like') {
            query[k] = {$regex: new RegExp(_cond, options)};
          } else if (spec === 'nlike') {
            query[k] = {$not: new RegExp(_cond, options)};
          } else if (spec === 'neq') {
            query[k] = {$ne: _cond};
          }
          else {
            //query[k] = {};
            query[k]['$' + spec] = _cond;
          }
        } else {
          if (cond === null) {
            // http://docs.mongodb.org/manual/reference/operator/query/type/
            // Null: 10
            query[k] = {$type: 10};
          } else {
            query[k] = _cond;
          }
        }
      });
    }
  });

  return query;
 }
```

Now I'm also able to use the "near" nested in the "and" object (I had to create a "2d" index instead of the "2dsphere" one)

Thanks for your support!

**Comment by kwiky** [comment]
Oh yes, to make this works, i have also remove the default order on _id on this method !

**Comment by geruiz** [comment]
This error still exists in the latest version .  This correction will be integrated soon?  Thanks

**Comment by viki53** [comment]
Hi,

We (@ebarault and I) have the same issue here, but not explicitly.

In fact, using the model directly everything is fine as we don't use the `$and` operator.

But, as we have to go through a parent model (`hasMany`+`belongsTo`) for the ACLs, the `$and` operator gets added to the final query (to filter the foreign key), it fails with Mongo saying it doesn't find the index for the GeoNear query.

**Comment by bugdanov** [comment]
Still relevant: :+1:  
https://github.com/strongloop/loopback-datasource-juggler/pull/993
https://github.com/strongloop/loopback-datasource-juggler/pull/993

**Comment by ebarault** [comment]
closed via #1216

**Comment by ebarault** [comment]
this can be closed now: 
see https://github.com/strongloop/loopback-datasource-juggler/pull/1216
and https://github.com/strongloop/loopback-connector-mongodb/pull/322

**Comment by dhmlau** [comment]
@willyyr , is it good to close?  See comments from @ebarault above.  Thanks.

**Comment by dhmlau** [comment]
Closing this due to inactivity.
